# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Fulll\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        Fulll\Infra\MessengerBus\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: app.messenger.command.bus }
        Fulll\Infra\MessengerBus\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: app.messenger.command.bus }


    Fulll\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

    fulll.command.createFleet:
        class: Fulll\Command\CreateFleetForUserCommand
        tags:
            - { name: console.command }

    fulll.command.registerVehicleInFleet:
        class: Fulll\Command\RegisterVehicleInFleetCommand
        tags:
            - { name: console.command }
